//Auth Constant
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT = "LOGOUT";

//Agent Constant
export const FETCH_AGENTS = "FETCH_AGENTS";
export const FETCH_AGENTS_SUCCESS = "FETCH_AGENTS_SUCCESS";
export const FETCH_AGENTS_FAILED = "FETCH_AGENTS_FAILED";

export const FETCH_FIREBASE_AGENTS = "FETCH_FIREBASE_AGENTS";
export const FETCH_FIREBASE_AGENTS_SUCCESS = "FETCH_FIREBASE_AGENTS_SUCCESS";
export const FETCH_FIREBASE_AGENTS_FAILED = "FETCH_FIREBASE_AGENTS_FAILED";

export const UPLOAD_AGENT_REQUEST = "UPLOAD_AGENT_REQUEST";
export const UPLOAD_AGENT_SUCCESS = "UPLOAD_AGENT_SUCCESS";
export const UPLOAD_AGENT_FAILED = "UPLOAD_AGENT_FAILED";

export const REUPLOAD_AGENT_REQUEST = "REUPLOAD_AGENT_REQUEST";
export const REUPLOAD_AGENT_REQUEST_SUCCESS = "REUPLOAD_AGENT_REQUEST_SUCCESS";
export const REUPLOAD_AGENT_REQUEST_FAILED = "REUPLOAD_AGENT_REQUEST_FAILED";

export const SAVE_AGENT_DRAFT = "SAVE_AGENT_DRAFT";
